### ISSUE TITLE
Broken upgrader in `SwordUpgradeTest`

### ISSUE THREAD

**Issue by mithrandi** [twisted/axiom#48]
The failure is in `axiom.test.test_upgrading.SwordUpgradeTest.testUpgradeWithMissingVersion`, but it only occurs when a certain dict ordering happens. `PYTHONHASHSEED=1290646218` produces one such ordering; this wasn't noticed before because the default seed doesn't produce the ordering that causes the failure.

First, the failing test traceback:
```
[ERROR]
Traceback (most recent call last):
  File "/home/mithrandi/code/axiom/axiom/test/test_upgrading.py", line 189, in afterUpgrade
    self._testPlayerAndSwordState(player, sword)
  File "/home/mithrandi/code/axiom/axiom/test/test_upgrading.py", line 368, in _testPlayerAndSwordState
    assert not sword.__legacy__
exceptions.AssertionError: 

axiom.test.test_upgrading.SwordUpgradeTest.testUpgradeWithMissingVersion
```
The assertion fires because the sword item has not been fully upgraded. The reason for this is that the `player1to2` upgrader does something that confuses the upgrade system. When the store is opened, Axiom looks at all of the currently-existing type versions in the store; any version that is out of date is handed to the upgrade manager in order to be upgraded. In the case of this test, the versions are `(Player, 1)` and `(Sword, 1)`. The upgrade manager loops over the types to be upgraded; for each type, it queries for all items of that type, and fully upgrades them (running upgraders until the current schema version is reached), before moving on to the next type/version.

The `player1to2` upgrader calls `upgradePlayerAndSword`, which retrieves both the sword and the player, and upgrades both of them to version 2. If this upgrader runs first, then the sword item will be at version 2. However, recall that the entry in the upgrader's list is `(Sword, 1)`; when it queries for items of this type, it obviously finds none. However, `(Sword, 2)` is not in its list, so the sword version 2 item is never upgraded to sword version 3. (The inverse problem does not occur when `sword1to2` runs first, because there is no Player v3 type).

How to proceed? I'm not sure if what this upgrader is doing should just be considered unsupported, and this upgrader (and corresponding part of the test) should be removed, or if we should find some way to make this functionality actually work (probably not impossible, but I don't see an easy way to make it work at the moment, so likely quite a lot of work).

**Comment by mithrandi** [comment]
I found a way to support this, along with another bug which I also fixed.
